# Generated by Django 4.0.4 on 2022-07-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main.tag'),
        ),
    ]
